### ISSUE TITLE
Circular dependency between buffer.js, encoding.js, and decoding.js

### ISSUE THREAD

**Issue by danny-andrews** [dmonad/lib0#16]
**Describe the bug**
I was running yjs code through rollup and got the following error:

```
(!) Circular dependencies
node_modules/lib0/encoding.js -> node_modules/lib0/buffer.js -> node_modules/lib0/encoding.js
node_modules/lib0/buffer.js -> node_modules/lib0/decoding.js -> node_modules/lib0/buffer.js
```

Not sure of the best way to go about fixing these since I'm not familiar with the codebase, but thought I'd make you aware of it if you weren't already. :)

**Comment by dmonad** [comment]
Hi @danny-andrews ,

nothing to worry about. I try to suppress these warnings whenever possible, but in this case, it is justified and won't lead to issues ;)

**Comment by danny-andrews** [comment]
Everything I've read seems to suggest it's advisable to avoid circular dependencies wherever possible, as they can lead to really confusing bugs, but to each their own.
