### ISSUE TITLE
Typo: 'repitition' to 'repetition'

### ISSUE THREAD

**Issue by jayaddison** [dmonad/lib0#27]
**Describe the bug**
Super small issue, but I noticed a typo here: https://github.com/dmonad/lib0/blob/fe162f494db2e0c7bdeada7a6bf97e98ae4f53dc/package.json#L295

`--repitition-time` should be `--repetition-time` (s/i/e)

**Additional context**
I considered opening a pull request to fix this, but it looks like it's used from a few dependent libraries that you have r/w access to, so it might be quicker to clean up centrally.  Glad to help if I can though!

**Comment by dmonad** [comment]
I'm a bit embarrassed about this :sweat_smile: 

Thanks for noticing. I make these kinds of mistakes a lot if I don't use a spellchecker.

**Comment by jayaddison** [comment]
No problem :)
