### ISSUE TITLE
array become object after encode/decode

### ISSUE THREAD

**Issue by neoimale** [dmonad/lib0#28]
I found that the statement `data instanceof Array` in [encoding.js](https://github.com/dmonad/lib0/blob/8eb3ba3e2615260225cd36bd56bb011cc6893f1a/encoding.js#L476) is incorrect when checking arrays across iframe, which expected to be true.

Maybe `Array.isArray` is preferred?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray

**Comment by dmonad** [comment]
This was the longest-standing issue here. This will be fixed in the next release!
