### ISSUE TITLE
node 12

### ISSUE THREAD

**Issue by holtwick** [dmonad/lib0#3]
https://github.com/dmonad/lib0/blob/3fd7d6af260cb4daa54b59d4ce2ace4a59c583d0/package.json#L55

lib0 seems to require node >= 13:

```
npm WARN notsup Unsupported engine for lib0@0.2.12: wanted: {"node":">=13"} (current: {"node":"12.14.1","npm":"6.13.4"})
```

While node 12 is the current stable version I think you might want to consider changing to node >= 12 if it does not have any side effects.

**Comment by dmonad** [comment]
Yeah, sorry..

**Comment by dmonad** [comment]
Thanks for bringing this up!
