### ISSUE TITLE
tree.findNode TypeScript definition error

### ISSUE THREAD

**Issue by FindAPattern** [dmonad/lib0#37]
I'm getting the following type error when compiling a project that depends on `lib0`:

```bash
node_modules/lib0/tree.d.ts(54,22): error TS2315: Type 'N' is not generic.
```

This line seems to cause the error:
https://github.com/dmonad/lib0/blob/73006dbdcbf9eda57d2fbfa10c431ee3b5470adc/tree.js#L297

The `N` class does not have a `@template` line in its doc comment. 

(Also, thanks for the _fantastic_ work you've done on Yjs and all of the supporting libraries.)

**Comment by dmonad** [comment]
Hi @FindAPattern I fixed the issue.

But please note that the tree implementation was created before I added typescript support (it's really old). I don't recommend using it in this state.

There is a comment at the top of the file that disables type checking. So there are probably more issues with the file.

I would be happy about a PR that adds typings to this module.
