### ISSUE TITLE
Reduce install size

### ISSUE THREAD

**Issue by benmerckx** [dmonad/lib0#39]
**Is your feature request related to a problem? Please describe.**

Install size for lib0 seems to be around 2.2MB. What causes the bloat is inclusion of the compiled test suite:
- dist/test.js.map (428Kb)
- dist/test.cjs.map (423Kb)
- dist/test.js (220Kb)
- dist/test.cjs (204Kb)

**Describe the solution you'd like**

These files could be added to .npmignore or other means of excluding them.

**Comment by dmonad** [comment]
Thank you for the suggestion. I implemented your suggestion and it really made a difference.

![image](https://user-images.githubusercontent.com/5553757/165991935-0d211eea-620c-4df5-bdb0-84bbe4b7689d.png)

This addition will be used in the next release.
