### ISSUE TITLE
Iframe issue in Brave browser with environment.js 

### ISSUE THREAD

**Issue by LucasGenoud** [dmonad/lib0#4]
We don't directly use lib0 but we use YJS and we allow to integrate a page from our app in an iframe, the page in the iframe doesn't load because of this error:
![image](https://user-images.githubusercontent.com/22954311/75327636-0b2ee380-587d-11ea-9cb5-36e2c63dd1b9.png)

It seems this issue only happens in brave browser

**Comment by dmonad** [comment]
Interesting.. thanks for reporting. I will fix it.

**Comment by dmonad** [comment]
I fixed this issue in 0.2.17. I wasn't able to reproduce this problem, so let me know if you still have problems.

**Comment by dmonad** [comment]
FYI `npm update` should bump lib0 in your project.

**Comment by LucasGenoud** [comment]
Thank you very much,
Altough in the YJS's package.json it's specified that the latest minor version should be installed, NPM keeped installing the 0.2.16 instead of 0.2.17 so i've made a pull request to force the latest version in yjs

**Comment by dmonad** [comment]
Does `npm update` not work for you?

**Comment by LucasGenoud** [comment]
It initially didn't update correctly but I've executed it again and it worked now... Also the initial issue seems to be fixed so thank you very much !

**Comment by dmonad** [comment]
Awesome! NP
