### ISSUE TITLE
Missing close method on LocalStoragePolyfill

### ISSUE THREAD

**Issue by ryanb** [dmonad/lib0#61]
I'm seeing `channel.bc.close is not a function` when attempting to disconnect a broadcast channel. This is showing up on my CI server when attempting to upgrade lib0 beyond 0.2.58. I believe this was introduced in [this commit](https://github.com/dmonad/lib0/commit/802d339a382f81ea888c0d55b797947d50b180e7) which added a call to `channel.bc.close`.

I assume my CI server is using `LocalStoragePolyfill` which doesn't respond to `close`. Should that method be added?

I can provide further details on this if needed.

**Comment by dmonad** [comment]
Right, thanks! I fixed the issue in 0.2.70.

**Comment by ryanb** [comment]
Wow, you're fast. Thanks!
