### ISSUE TITLE
Deprecated node:crypto is bricking deployments to fly.io

### ISSUE THREAD

**Issue by rafcole** [dmonad/lib0#69]
Not much to say, completely fresh clone of yWebsocket can't be deployed because of Node:crypto deprecation
![image](https://github.com/dmonad/lib0/assets/39354464/04f900bc-3e57-4bcd-9f8b-d1b636ca143a)

**Comment by dmonad** [comment]
I'm not deprecated. You are deprecated. Lol

(You are running a deprecated node version)

Seriously, please open a proper ticket if that is not the case.
