### ISSUE TITLE
ObservableV2 does not accept interfaces

### ISSUE THREAD

**Issue by somebody1234** [dmonad/lib0#72]
```ts
class ObservableV2<EVENTS extends {
    [key: string]: (...arg0: any[]) => void;
}> {}
```
rejects interfaces because interfaces don't have an index signature.
would it be possible to do this instead?
```ts
class ObservableV2<EVENTS extends {
    [key in EVENT_TYPES]: (...arg0: any[]) => void;
}, EVENT_TYPES extends keyof EVENTS = keyof EVENTS> {}
```

**Comment by somebody1234** [comment]
Also `NAME extends string` should probably be `NAME extends keyof EVENTS` (or `EVENT_TYPES`) so that autocomplete actually works (?)

**Comment by Frizi** [comment]
I believe that the `EVENT_TYPES` generic could also be avoided.

```ts
class ObservableV2<EVENTS extends {
    [key in keyof EVENTS]: (...arg0: any[]) => void;
}> {

  on<NAME extends keyof EVENTS>(name: NAME, f: EVENTS[NAME]) {
   // ...
  }
}
```

This variant seems to support interfaces just fine, and autocomplete works too.

**Comment by dmonad** [comment]
Sometimes I don't know if I should take an issue seriously or not. You didn't bother to give any details or hints to the issue you are describing. I can't find EVENT_TYPEs.  I'm not using typescript.

Please help me save some time by opening a new ticket and filling out the template that I carefully provided.

**Comment by dmonad** [comment]
I looked through the codebase and I think I found what you mean. Note: ObservableV2 is still not done (should be marked as experimental). I will mark it stable once I use it myself in one of my projects..
