### ISSUE TITLE
ObservableV2 does not accept an interface as its generic parameter

### ISSUE THREAD

**Issue by somebody1234** [dmonad/lib0#76]
**Describe the bug**
`ObservableV2` does not accept `A` as a generic parameter if `A` is not a `@typedef`.
Related to:
- #72

**To Reproduce**
```js
import { ObservableV2 } from 'lib0/observable';

class A {
  /** @type {() => void} */ a;
}

/** @type {ObservableV2<A>} */
const what = /** @type {any} */ ({});
```

See [this TypeScript playground link](https://www.typescriptlang.org/play?filetype=js#code/MYGwhgzhAECC0G8BQ1oHoBUHoAEAuAngA4CmiAFAJTQC8AfNAG4D2AlgCYC+0Ga0YAbiSckSTNnzEyCAPIAjCCQBOjMHJAkAagCYAPLDrdeSYMwB2EPNADuACzBWa6LLkKlEYMwSN9yCTpRCouIo2PKKKmoa0KCQMERKzHhJUgB0oaG4ALbM7ACu0cwKyqrqJKFowViZABKe7BowZmBZJOzQJIwkZngQ6Ty4JAAepEqsrT1gIBkDACq2rDCL0HKQrMBTIAT80ORyJHh4ytBubdT5RCDrDmTMAGbQ4SVRJAA0NgvAtjasICDQShIlzAwDIT0iZWgrDMJ1s5QGZmGVkBGkgJH6GEy+BIWWBR0QCAA2gBrEgEABc0EsYzMAHMALqUu55MzAPCsczkVLczwESjklgcTjcACimhFADlZgBlCpIYZEZhKKyxKCPYoQjQ6RAoGLmal5NlK3bUZCoVAhc2obDS5itaDsEgQYD9K0SU6IACyYCIump0Np72lB10vLohl15uMVrwCz6AH0ihEukoYE5EdZoN6iFRdSJdZbra4cXjpKSCPdoGLJTLoAAyKl4Gm07gS2CekWRiREMBKFqINsd7jNVpd3A9vtZRDVqXSwmDkX07h3LuVVDmXYjt7QO6myMAg55JQwleofMW6pR4u48D4hDlysz2sN-101vtztXnAT-sIBfDlp4SLb9e1-J85wXJcd1XXVzFBTdAPeXcdStQsvx-KdEG5VJeW4XtaQgfceDXc1TAsKx4weJwuR5JQCOoegUKtWFFlSe47nILd3nEVwpA8LwfF2SjKEoIidxonC6IgUSrREGM4zYsxOMQ5x3T4hBcOIoTdxk6Bz1UsdsRvG5EAfB5wPrRtm3fDtDIwgcPwA0d0NAqcEHA+cPyg09rRI9iENaJC9ytMjLGgJMSmUNMWITCKVCi1JaQOZTWl01BWAecg4pTGAAEIaCcFlHTuaEziYq1soSx0NCOchdzEjLdkq1NUggVgAC8yAKpwAAZguY1BY1YxMNRy1JqoOEgUpINLzTkua81EC9MSvEUslYKwwGgLd2k6bo8FSOA-gPWlFiOQFdq6HpoCuSxuii2EHBus7uhOZhYSAgYIFIYAMtYNptsAn5jsBUFWC6D6Oiug6u0M5J2He+ZlggWxmAKdoNjwL4OiGUEiHZfVYa-I5jLvMyq3FWdLNfFtoAXOzXIcodAfteYyD266t1dAYQMnRAAAVXMm1NdA8yDDH4KToDZyXaTyCZekezbAX4IhLn+9pkkhjmrFuo5ESUbnow6darGm958Ok8r0D4UwiG2TZnrug2YC1zxJb7bYStTKwtayMBSSpI8yFjJ6zHenWoRgHENqOTX3r1+7UyVyWyAgPIFGAMZ9naOxfhDuEof26B7DMBpjmWDY-jabmDzwI8YVgJRPdSO5EiychyCG2LRoSpK8Gm6gAB8h+2khM2zKhKFSVQQDyJ0p9bpURRBWw6toBgOOwy2RMW3VHWpZhtioa3u9SEbkwe9Nx6zH1czPYQgA).
(Note that the implementation of `lib0/observable` has been copied into the link - the TS playground seems to have problems importing its type definitons from npm)

**Expected behavior**
No type errors

See [this TypeScript playground link](https://www.typescriptlang.org/play?filetype=js#code/MYGwhgzhAECC0G8BQ1oHoBUHoAEAuAngA4CmiAFAJTQC8AfNAG4D2AlgCYC+0Ga0YAbiSckSTNnzEyCAPIAjCCQBOjMHJAkAagCYAPLDrdeSYMwB2EPNADuACzBWa6LLkKlEYMwSN9yCTpRCouIo2PKKKmoa0KCQMERKzHhJUgB0oaG4ALbM7ACu0cwKyqrqJKFowViZABKe7BowZmBZJOzQJIwkZngQ6Ty4JAAepEqsrT1gIBkDACq2rDCL0HKQrMBTIAT80ORyJHh4ytBubdT5RCDrDmTMAGbQ4SVRJAA0NgvAtjasICDQShIlzAwDIT0iZWgrDMJ1s5QGZmGVkBGkgJH6GEy+BIWWBR0QCAA2gBrEjbaHQUkEe7QACimlpADlZgBlAC6AC5oHc8mZgHhWOZyKkRZ4CJQOSwOJxuPSmayKkhhkRmEorLEoI9ihCNDpECgYuZLEo8vzVbtqMhUKgQtbUNgWcxWtB2CQIMB+naJKdEABZMBEXTG6EAc3eLIOujFdEMButxjteAWfQA+kUIl0lDAnIjrNB-UQqAaRAbbfbXDi8dIqTS5cyWdAAGTQYNmEPcRmwX20uMSIhgJQtRCd7vcZqtXu4fuDrKIOuswkj2ls7h3XuVVDmXbjt7cy1xgEHPJKGFr1Alm3VeMV3HgfEIGsPecN5ut9vQJeTnDTocIJdjlp4XLb8B1-Z9Fy7ZdV3XA1zFBbdAPeO59ztMtrxAmdUAQEVUjFbgBxDCADx4DdrVMCwrBTB4nGFUUlEI6h6H1O1UCTRZUnuO5yB3d5xFcKQPC8HxdioyhKGI7laNw+iIHEu0RETZMOLMbjEOcb0BIQPCSJE5C5OgC91K-I5bxuRBHzpBl6ybFs8DGNsO0gr8f1nP9IIAid0JcucrIXJcV25GDNzuB5VNaJCULIo0rHTEplGzWF2LTbVMz6EMDjCkh9NQVhQtilR4ugABCGgnF5V07mhM5mJY-LUtSV0NCOchkIk3Ldjq+LUggVgAC8yFKpwAAZIpYxLU06rMGpIJqSEy7LrQUxbi1ES9MWvWkslYKwwGgHd2k6bo8FSOA-kPENFiOQEDq6HpoCuSxukKpMHHuy7uhOZhYSAgYIFIYBctYNo9sAn4zsBUFWC6b6Olu47e2M3IvvmZYIFsZgCnaDY8C+DohlBIgBSNBH0JMqtzLJWtfJfWz7PfT8vNA1z-xB515jIQ67p3T0Bgw38AAUmYOeLdHA-zDH4GToHZyWQzyCZelhV6BzIANLiB9pkhhzmrAeo5ESUHmEw6LarEy94CNkmqbT4UwiG2TY3seg2YC1zxJcHbZKqzKwtayMBSRbY8yBeqwzC+nWoRgHFtqOTWvr1p6syVnbASDhRgDGfZ2jsX4Q7hWGjugewzAaY5lg2P42h5w88GPGFYCUT3UjuRIsnIcg2ImlKuvSvB5ugAAfQe9pIPMCyoShUlUEA8jdSeW9VWkQVsFraAYLicMtsSVoNV1jWYbYqGt8bUmSjNCpzMf8wDItz2EIA) for a demo of a potential solution.

**Screenshots**
N/A

**Environment Information**
 - Platform: any
 - Version: 0.2.85

**Additional context**
this is a potential solution:
```js
/**
 * @template {{[key in keyof EVENTS]: function(...any):void}} EVENTS
 */
```
it is implemented in the link in the "expected behavior" section above

it isn't valid JSDoc syntax though, so it may not be an option if you're planning on generating docs from the source.

**Comment by dmonad** [comment]
Okay, we can implement it like that. See my last commit. I don't know why this would be useful. Also, I'm not sure if a self-referencing template is a good idea or not, just because it is still working. This also allows the use of symbols and numbers as event names (which is not necessarily a good thing).
