### ISSUE TITLE
Discouraged `unload` event used in indexeddb

### ISSUE THREAD

**Issue by westonruter** [dmonad/lib0#78]
There is currently a use of the `unload` event in indexeddb:

https://github.com/dmonad/lib0/blob/262570288c55ee613c7883d34891b5f9584410af/indexeddb.js#L52

This event handler is being [deprecated by Chrome](https://developer.chrome.com/blog/deprecating-unload/). Its use is also [warned against on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event) as it is unreliable and it disables bfcache.

See Chrome's [suggested alternatives](https://developer.chrome.com/blog/deprecating-unload/#alternatives-to-unload-events), including the `pagehide` event.

**Comment by dmonad** [comment]
There is probably a reason why I added the unload event. But that was 4 years ago. So let's try without ..
