### ISSUE TITLE
support and honor NO_COLOR env variable

### ISSUE THREAD

**Issue by Loki-Afro** [dmonad/lib0#91]
**Is your feature request related to a problem? Please describe.**
NO_COLOR is de-facto standard and it frustrates me when some libs, tools wahtever don't support it

**Describe the solution you'd like**
honor NO_COLOR=true

**Describe alternatives you've considered**
none

see also https://no-color.org/

**Comment by dmonad** [comment]
There's already the `--no-colors` parameter that disables colors. But if there's a website for `NO_COLOR`, then I have to honor it. This is implemented in the latest release.
