### ISSUE TITLE
isomorphic-webcrypto not resolved correctly with react-native expo

### ISSUE THREAD

**Issue by aurmartin** [dmonad/lib0#93]
**Describe the bug**
The random module does not work with react-native expo.

I have followed the instructions in the README.md (installed isomorphic-webcrypto and enabled unstable_enablePackageExports).

The isomorphic-webcrypto module isn't resolved correctly.

Error message: `TypeError: Cannot read property 'ensureSecure' of undefined, js engine: hermes`

Stacktrace:

![image](https://github.com/user-attachments/assets/34b321aa-e751-436e-b921-67defcf0926c)

**To Reproduce**
1. `npx create-expo-app@latest`
2. Import `import * as random from 'lib0/random'` and use `random.rand()`
3. `npx expo start`
4. Open on android emulator

**Expected behavior**
Lib0 random module works with react-native expo.

**Environment Information**
- Expo: 51.0.28
 - Lib0: 0.2.98

**Additional context**
A workaround I have found is to hack the metro resolver:

```javascript
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");

/** @type {import('expo/metro-config').MetroConfig} */
const defaultConfig = getDefaultConfig(__dirname);

console.warn("THERE")

const config = defaultConfig;

config.resolver.unstable_enablePackageExports = true;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (platform !== "web" && moduleName === "isomorphic-webcrypto") {
    return {
      filePath:
        __dirname + "/node_modules/isomorphic-webcrypto/src/react-native.js",
      type: "sourceFile",
    };
  }

  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
```

**Comment by aurmartin** [comment]
I also opened a PR with a fix for this issue: https://github.com/dmonad/lib0/pull/94

**Comment by dmonad** [comment]
Thanks for the PR! I'll publish a new release shortly. Could you please check whether the steps in the readme work to get this to work in react-native? If not, please update the readme.

**Comment by dmonad** [comment]
Anything that works! Happy to merge if you want to share your working approach.

**Comment by aurmartin** [comment]
My approach only works for `crypto.getRandomValues` but the `crypto.subtle` module also used by lib0 is not provided by [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values).

**Comment by dmonad** [comment]
Phew.. what a mess.. 

Anyway, happy it works for you. Thanks for the fix. At least there are some ways to get it to work.
